### ISSUE TITLE
Missing "Heroic" factory name in the web guide ?

### ISSUE THREAD

**Issue by jhice** [heroiclabs/heroiclabs-sdk-web#11]
Hi there,
just trying your SDK following the web guide and got a "Client not defined" error, because the sample is missing _Heroic_.Client. Visiting the Github page gave me the solution with the Heroic export name for using the SDK.

So I dont know if it is intentional or not, but having a certain experience in programming (not specifically in Javascript) I face this problem, I suppose others or beginners could miss the first step here.

Am I missing a good practice here or something ^^ ?
Can you tell me more, thanks.

**Comment by mofirouz** [comment]
Hi there,

That's a good question. 

The main reason why it's not mentioned on the guide is that you can use different types of module loaders in JS and that will change the namespace that the functions/objects are mapped to. Historically, there was a bug with the UMD module loader that had put the namespace as `window.main` but we've seen fixed that and the change had not been reflected on the documentation.

I'll make a note to add the `Heroic` prefix to the SDK Web Guide on the website.

Cheers

**Comment by jhice** [comment]
Ok, I understand.
Thanks for replying.
