### ISSUE TITLE
Session save and restore, and JSON object storage

### ISSUE THREAD

**Issue by jhice** [heroiclabs/heroiclabs-sdk-web#12]
Hi again,

I faced a kind of issue relative to storage session.
Following the guide lead to store the session as _"[object Object]"_, because it not JSON stringified before saving.

With `localStorage.setItem('session', JSON.stringify(session));` the session is stored correctly, as object.

After that, we can load the session by using **the token** stored :
`cachedSession = JSON.parse(localStorage.getItem("session"));`
`session = new Heroic.Session(cachedSession._token);`
Else it creates a malformed session.

Indeed in the API reference, Session needs a token as only parameter, and not a Session object.

**Comment by mofirouz** [comment]
Hi there. Yes - you are absolutely right. I'll make a note to fix this in the guide. Thanks for the heads up and letting me know. Cheers.

**Comment by jhice** [comment]
Great, thanks.
