### ISSUE TITLE
src/match.js - add "data" property for ending a match

### ISSUE THREAD

**Issue by maxg7** [heroiclabs/heroiclabs-sdk-web#16]
I propose adding a "data" property on the matches.js sdk. This way, if someone wins the game (or loses) you can file that metadata along with the match rather than having to (a) recalculate on the fly or (b) file win/lose on the previous non-ending turn making "yourself" the next turn submitter to then be able to end the match.

If there's a different best practice I'm all ears.

```
/**
 * End a match.
 */
export class MatchTurnEndRequest extends ApiRequest {

  /**
   * @param  {Session} session Session identifying the account making this request.
   * @param  {String} matchId The match ID to end.
   * @return {MatchTurnEndRequest} An instance of this object.
   */
  constructor(session, matchId, data=null) {
    var body = {'action': 'end', 'data': data};
    super('POST', '/v0/gamer/match/' + matchId, session, body);
  }
}
```

**Comment by mofirouz** [comment]
You should append your custom data before you send the end/leave match request. This data can either be your match progress information, or match summary as you mentioned.
